# Core module
obj-y						+= fiio_uevent.o
obj-y						+= fiio_i2c_interface.o
obj-$(CONFIG_FIIO_DEBUG)	 += debug.o

obj-$(CONFIG_FIIO_SENSORS_MMA865X)	 += mma8653.o

obj-$(CONFIG_FIIO_PLAYER_CHECK)	 += check_player.o

obj-$(CONFIG_FIIO_IO_CTRL) += fiio_ctrl.o

obj-$(CONFIG_FIIO_SENSORS_LIS3DH)	 += lis3dh_acc.o

obj-$(CONFIG_FIIO_CC_TUSB320)	 += tusb320.o

obj-$(CONFIG_FIIO_SENSORS_LIS3DSH)	 += lis3dsh_fiio.o

obj-$(CONFIG_FIIO_SENSORS_STK8323)	 += stk8323.o

obj-$(CONFIG_FIIO_SENSORS_STK832X)	 += stk832x.o
